services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "20524219"
      POSTGRES_DB: studentapp
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 5; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
